version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driver_app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload --reload-include settings.json"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
    - db
    healthcheck:
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
      test: "curl -f http://api:8000/"

  geodata_generator:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python geodata_generator.py"
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      api:
        condition: service_healthy

volumes:
  db-data:
